### ISSUE TITLE
Python enabled, plugin gives error

### ISSUE THREAD

**Issue by johnbiederstedt** [ColinKennedy/vim-python-function-expander#1]
I have python and python3 enabled, but the plugin still gives an error:
Error detected while processing /home/myself/host/.vim/bundle/vim-python-function-expander/plugin/python-function-expander.vim:
line    2:
vim-python-function-expander requires Python. Cannot continue loading this plugin
Error detected while processing /home/myself/host/.vim/bundle/vim-python-function-expander/plugin/trimmer.vim:
line    2:
vim-python-function-expander requires Python. Cannot continue loading this plugin

My vim version info:

:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  5 2018 12:45:08)
Included patches: 1-1689
Extra patches: 8.0.0056
Compiled by myself@090e8549e9a4
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +clipboard       +dialog_con_gui  +file_in_path    +job             +menu            -mouse_sysmouse  +persistent_undo +scrollbind      +tcl/dyn         +visual          +xim
+arabic          +cmdline_compl   +diff            +find_in_path    +jumplist        +mksession       +mouse_urxvt     +postscript      +signs           +terminfo        +visualextra     +xsmp_interact
+autocmd         +cmdline_hist    +digraphs        +float           +keymap          +modify_fname    +mouse_xterm     +printer         +smartindent     +termresponse    +viminfo         +xterm_clipboard
+balloon_eval    +cmdline_info    +dnd             +folding         +langmap         +mouse           +multi_byte      +profile         +startuptime     +textobjects     +vreplace        -xterm_save
+browse          +comments        -ebcdic          -footer          +libcall         +mouseshape      +multi_lang      +python/dyn      +statusline      +timers          +wildignore      +xpm
++builtin_terms  +conceal         +emacs_tags      +fork()          +linebreak       +mouse_dec       -mzscheme        +python3/dyn     -sun_workshop    +title           +wildmenu
+byte_offset     +cryptv          +eval            +gettext         +lispindent      +mouse_gpm       +netbeans_intg   +quickfix        +syntax          +toolbar         +windows
+channel         +cscope          +ex_extra        -hangul_input    +listcmds        -mouse_jsbterm   +packages        +reltime         +tag_binary      +user_commands   +writebackup
+cindent         +cursorbind      +extra_search    +iconv           +localmap        +mouse_netterm   +path_extra      +rightleft       +tag_old_static  +vertsplit       +X11
+clientserver    +cursorshape     +farsi           +insert_expand   +lua/dyn         +mouse_sgr       +perl/dyn        +ruby/dyn        -tag_any_white   +virtualedit     -xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.
0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/p
ango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/l
ibbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.
0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo
 -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/incl
ude/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/g
lib-2.0/include   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -
latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-
2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgm
odule-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux   -lacl -lattr -lgpm -ldl   -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linu
x-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt   -L/usr/lib/x86_64-linux-gnu -ltclstub8.6 -ldl -lz -lpthread -lieee -lm

**Comment by ColinKennedy** [comment]
vim-python-function-expander runs on either Python 2 or 3. I thought Vim recommended to use the `pythonx` command for Python 2+3 code ([:help pxyversion](https://vim-jp.org/vimdoc-en/if_pyth.html#python_x)). Maybe I misunderstood that part of the docs.

What is the output of following commands?

```
:echo has('python')
:echo has('python3')
:echo has('pythonx')

:python print('Hello, world!')
:python3 print('Hello, world!')
:pythonx print('Hello, world!')
:set pyxversion
```

**Comment by Kazy** [comment]
The same thing happens to me on Neovim, compiled from master yesterday:
```
% vim --version
NVIM v0.3.2-837-g6fe740c7a
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/akear/.cache/yay/neovim-git/src/neovim-git/build/config -I/home/akear/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/akear/.cache/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/akear/.cache/yay/neovim-git/src/neovim-git/build/include
Compiled by akear@archlinux

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```
:echo has('python')
1
:echo has('python3')
1
:echo has('pythonx')
0

:python print('Hello, world!')
Hello, world!
:python3 print('Hello, world!')
Hello, world!
:pythonx print('Hello, world!')
E492: Not an editor command: pythonx print('Hello, world!')
:set pyxversion
E518: Unknown option: pyxversion
```

Thanks !

**Comment by wookayin** [comment]
The `pythonx` feature is available with vim >= 8.0.0251. Not in neovim.

**Comment by wookayin** [comment]
Since neovim is also widely being used these days, it would be great to support a fallback to python3, for older versions of vim and **neovim**. Neovim already has [pythonx provider support](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim), so it would just suffice to call `:python` instead of `:pythonx` in this case.

I don't think you need to support python 2 with huge effort as of 2018.

**Comment by ColinKennedy** [comment]
As @wookayin  pointed out, the command which I was using to check for Python is only available in more recent Vim versions. I wasn't aware of this which is where the confusion came started. Thank you for clarifying.

I've updated the plug-in and it should now work for Python 2 or 3, vim/neovim old and new.

The PR is available here: https://github.com/ColinKennedy/vim-python-function-expander/pull/2

@johnbiederstedt and @Kazy please pull that branch and let me know if that branch works for you

**Comment by ColinKennedy** [comment]
Hi @johnbiederstedt I've merged the PR to support older Vim versions + neovim so I'm closing this ticket now. That said, if you continue to have issues in your set up, please feel free to re-open this ticket.
